name: C2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - black
  - flake8
  - pytest
  - pandas
  - "numpy<2.5"   
  - numba       
  - pip
  - pip:
      - sqlmodel
      - selenium
      - plotly
      - streamlit
      - pandas-stubs