name: C2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - black
  - flake8
  - pytest
  - numpy
  - numba
  - plotly
  - streamlit
  - pip
  
  - pip:
      - sqlmodel
      - selenium